export let techDomains = [
    { value: "Artificial Intelligence", label: "Artificial Intelligence" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Deep Learning", label: "Deep Learning" },
    { value: "Natural Language Processing", label: "Natural Language Processing" },
    { value: "Data Science", label: "Data Science" },
    { value: "Big Data", label: "Big Data" },
    { value: "Data Mining", label: "Data Mining" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Ethical Hacking", label: "Ethical Hacking" },
    { value: "Cloud Computing", label: "Cloud Computing" },
    { value: "Edge Computing", label: "Edge Computing" },
    { value: "Software Development", label: "Software Development" },
    { value: "Web Development", label: "Web Development" },
    { value: "React.js", label: "React.js" },
    { value: "Angular.js", label: "Angular.js" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Mobile App Development", label: "Mobile App Development" },
    { value: "Flutter", label: "Flutter" },
    { value: "React Native", label: "React Native" },
    { value: "Internet of Things", label: "Internet of Things" },
    { value: "Wearable Technology", label: "Wearable Technology" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Cryptocurrency", label: "Cryptocurrency" },
    { value: "Augmented Reality", label: "Augmented Reality" },
    { value: "Virtual Reality", label: "Virtual Reality" },
    { value: "Mixed Reality", label: "Mixed Reality" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "C++", label: "C++" },
    { value: "C#", label: "C#" },
    { value: "Ruby", label: "Ruby" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Go", label: "Go" },
    { value: "Rust", label: "Rust" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "SQL", label: "SQL" },
    { value: "NoSQL", label: "NoSQL" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "TensorFlow", label: "TensorFlow" },
    { value: "PyTorch", label: "PyTorch" },
    { value: "Pandas", label: "Pandas" },
    { value: "NumPy", label: "NumPy" },
    { value: "SciPy", label: "SciPy" },
    { value: "Matplotlib", label: "Matplotlib" },
    { value: "Seaborn", label: "Seaborn" },
    { value: "Scikit-learn", label: "Scikit-learn" },
    { value: "Keras", label: "Keras" },
    { value: "Jupyter Notebook", label: "Jupyter Notebook" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "Bitbucket", label: "Bitbucket" },
    { value: "GitLab", label: "GitLab" },
    { value: "Other", label: "Other" }
]
