const pythonChapters = [
    "Installation",
    "Control Statements",
    "Strings",
    "Lists",
    "Tuples",
    "Dictionary",
    "Modules",
    "Exceptions",
    "Date and Time",
    "File I/O",
    "Programs",
    // ... add more chapters as needed
    "Regular Expressions",
    "Object-Oriented Programming",
    "Inheritance",
    "Polymorphism",
    "Abstraction",
    "Encapsulation",
    "Generators",
    "Decorators",
    "Lambda Functions",
    "List Comprehensions",
    "Set Data Type",
    "Database Connectivity",
    "Multithreading",
    "Networking",
    "Web Scraping",
    "Data Visualization",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Web Development with Flask",
    "Web Development with Django",
    "Unit Testing",
    "Debugging Techniques",
    "Best Practices",
    "Coding Style",
    "Performance Optimization",
    "Security",
    "Design Patterns",
    "API Development",
    "Cloud Computing",
    "Big Data and Hadoop",
    "Data Science",
    "Artificial Intelligence",
    "Blockchain and Cryptocurrency",
    "Quantum Computing",
    "Ethical Hacking",
    "Game Development",
    "GUI Development",
    "Mobile App Development",
  ];

export default pythonChapters;