export let tags = [
    { value: "Algorithms", label: "Algorithms" },
    { value: "Data Structures", label: "Data Structures" },
    { value: "Artificial Intelligence", label: "Artificial Intelligence" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Deep Learning", label: "Deep Learning" },
    { value: "Natural Language Processing", label: "Natural Language Processing" },
    { value: "Computer Vision", label: "Computer Vision" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Cloud Computing", label: "Cloud Computing" },
    { value: "Edge Computing", label: "Edge Computing" },
    { value: "Software Engineering", label: "Software Engineering" },
    { value: "Programming Languages", label: "Programming Languages" },
    { value: "Web Development", label: "Web Development" },
    { value: "React.js", label: "React.js" },
    { value: "Angular.js", label: "Angular.js" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Mobile App Development", label: "Mobile App Development" },
    { value: "Flutter", label: "Flutter" },
    { value: "React Native", label: "React Native" },
    { value: "Internet of Things", label: "Internet of Things" },
    { value: "Wearable Technology", label: "Wearable Technology" },
    { value: "Blockchain", label: "Blockchain" },
    { value: "Cryptocurrency", label: "Cryptocurrency" },
    { value: "Augmented Reality", label: "Augmented Reality" },
    { value: "Virtual Reality", label: "Virtual Reality" },
    { value: "Mixed Reality", label: "Mixed Reality" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "C++", label: "C++" },
    { value: "C#", label: "C#" },
    { value: "Ruby", label: "Ruby" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Go", label: "Go" },
    { value: "Rust", label: "Rust" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "SQL", label: "SQL" },
    { value: "NoSQL", label: "NoSQL" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "TensorFlow", label: "TensorFlow" },
    { value: "PyTorch", label: "PyTorch" },
    { value: "Pandas", label: "Pandas" },
    { value: "NumPy", label: "NumPy" },
    { value: "SciPy", label: "SciPy" },
    { value: "Matplotlib", label: "Matplotlib" },
    { value: "Seaborn", label: "Seaborn" },
    { value: "Scikit-learn", label: "Scikit-learn" },
    { value: "Keras", label: "Keras" },
    { value: "Jupyter Notebook", label: "Jupyter Notebook" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "Bitbucket", label: "Bitbucket" },
    { value: "GitLab", label: "GitLab" },
    { value: "Other", label: "Other" },
    { value: "AWS", label: "AWS" },
    { value: "EC2", label: "EC2" },
    { value: "S3", label: "S3" },
    { value: "Lambda", label: "Lambda" },
    { value: "DynamoDB", label: "DynamoDB" },
    { value: "RDS", label: "RDS" },
    { value: "Elastic Beanstalk", label: "Elastic Beanstalk" },
    { value: "VPC", label: "VPC" },
    { value: "CloudFormation", label: "CloudFormation" },
    { value: "CloudWatch", label: "CloudWatch" },
    { value: "IAM", label: "IAM" },
    { value: "Cognito", label: "Cognito" },
    { value: "Route 53", label: "Route 53" },
    { value: "SNS", label: "SNS" },
    { value: "SQS", label: "SQS" },
    { value: "SES", label: "SES" },
    { value: "Elasticsearch", label: "Elasticsearch" },
    { value: "Aurora", label: "Aurora" },
    { value: "Redshift", label: "Redshift" },
    { value: "Glue", label: "Glue" },
    { value: "Step Functions", label: "Step Functions" },
    { value: "EMR", label: "EMR" },
    { value: "Data Pipeline", label: "Data Pipeline" },
    { value: "Kinesis", label: "Kinesis" },
    { value: "Elastic Transcoder", label: "Elastic Transcoder" },
    { value: "Elasticache", label: "Elasticache" },
    { value: "Neptune", label: "Neptune" },
    { value: "Quicksight", label: "Quicksight" },
    { value: "Data Warehouse", label: "Data Warehouse" },
    { value: "BigQuery", label: "BigQuery" },
    { value: "Snowflake", label: "Snowflake" },
    { value: "Redshift", label: "Redshift" },
    { value: "Teradata", label: "Teradata" },
    { value: "Azure SQL Data Warehouse", label: "Azure SQL Data Warehouse" },
    { value: "Google Cloud Storage", label: "Google Cloud Storage" },
    { value: "Hadoop", label: "Hadoop" },
    { value: "Hive", label: "Hive" },
    { value: "Pig", label: "Pig" },
    { value: "Spark", label: "Spark" },
    { value: "HBase", label: "HBase" },
    { value: "Cassandra", label: "Cassandra" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Neo4j", label: "Neo4j" },
    { value: "CouchDB", label: "CouchDB" },
    { value: "Couchbase", label: "Couchbase" },
    { value: "Firebase", label: "Firebase" },
    { value: "Riak", label: "Riak" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MySQL", label: "MySQL" },
    { value: "SQLite", label: "SQLite" },
    { value: "MariaDB", label: "MariaDB" },
    { value: "Oracle Database", label: "Oracle Database" },
    { value: "SQL Server", label: "SQL Server" },
    { value: "DB2", label: "DB2" },
    { value: "SAP HANA", label: "SAP HANA" },
    { value: "Teradata", label: "Teradata" },
    { value: "Informix", label: "Informix" },
    { value: "Sybase", label: "Sybase" },
    { value: "Access", label: "Access" },
    { value: "Ingres", label: "Ingres" },
    { value: "Progress", label: "Progress" },
    { value: "Firebird", label: "Firebird" },
    { value: "FileMaker", label: "FileMaker" },
    { value: "RethinkDB", label: "RethinkDB" },
    { value: "CockroachDB", label: "CockroachDB" },
    { value: "Memcached", label: "Memcached" },
    { value: "Redis", label: "Redis" },
    { value: "ZooKeeper", label: "ZooKeeper" },
    { value: "etcd", label: "etcd" },
    { value: "Consul", label: "Consul" },
    { value: "DynamoDB", label: "DynamoDB" },
    { value: "Azure Cosmos DB", label: "Azure Cosmos DB" }]